DELETE http://localhost:8080/events/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImV4cCI6MTcwNTcxNTkxNywidXNlcklkIjoyfQ.cBw3mSglfKPomBFFYSTq2EKedooSonayCxTxiogGPEA
