PUT http://localhost:8080/events/3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImV4cCI6MTcwNTcxNTkxNywidXNlcklkIjoyfQ.cBw3mSglfKPomBFFYSTq2EKedooSonayCxTxiogGPEA

{
    "name" : "Updated test event",
    "description" : "Updated test event",
    "location" : "Test location updated",
    "dateTime" : "2025-01-01T15:30:00Z"
}